/**
 * Learning Types
 *
 * TypeScript types for the learning experience, LLM interactions, and tutoring.
 */

import type { CurriculumTopic, Student } from './database';

// =============================================================================
// CONTEXT TYPES
// =============================================================================

/**
 * Student context for LLM prompts
 */
export interface StudentContext {
  student_id: string;
  first_name: string;
  grade_level: string;
  curriculum_level: number;
  skill_level: 'not_started' | 'learning' | 'practicing' | 'mastered';
  recent_accuracy: number;
  strengths?: string[];
  weaknesses?: string[];
}

/**
 * Topic context for LLM prompts
 */
export interface TopicContext {
  topic_id: string;
  code: string;
  title: string;
  description: string;
  strand: string;
  sub_strand?: string;
  level: number;
  elaborations?: string[];
}

/**
 * Full tutoring context combining student, topic, and session info
 */
export interface TutoringContext {
  student: StudentContext;
  topic: TopicContext;
  session: {
    session_id: string;
    questions_completed: number;
    recent_performance: number;
  };
}

// =============================================================================
// QUESTION TYPES
// =============================================================================

/**
 * Question generated by LLM
 */
export interface GeneratedQuestion {
  question_text: string;
  question_type: 'multiple_choice' | 'short_answer' | 'problem_solving';
  difficulty: 'easy' | 'medium' | 'hard';
  hints: string[];
  correct_answer: string;
  solution_steps: string[];
  focuses_on: string;
}

/**
 * Response from question generation
 */
export interface QuestionGenerationResponse {
  questions: GeneratedQuestion[];
}

/**
 * Question with metadata for display
 */
export interface Question extends GeneratedQuestion {
  id: string;
  topic_id: string;
  created_at: string;
}

// =============================================================================
// ANSWER EVALUATION TYPES
// =============================================================================

/**
 * Answer evaluation from LLM
 */
export interface AnswerEvaluation {
  is_correct: boolean;
  accuracy_score: number; // 0.0 to 1.0
  feedback: string;
  conceptual_understanding: 'strong' | 'developing' | 'needs_work';
  identified_weakness: string | null;
  suggested_hint: string | null;
  encouragement: string;
}

/**
 * Student's answer submission
 */
export interface AnswerSubmission {
  question_id: string;
  student_answer: string;
  time_spent_seconds: number;
  hints_used: number;
}

// =============================================================================
// PROGRESS TYPES
// =============================================================================

/**
 * Progress analysis from LLM
 */
export interface ProgressAnalysis {
  strengths: string[];
  weaknesses: string[];
  patterns: string;
  recommendations: string;
}

/**
 * Progress update data
 */
export interface ProgressUpdate {
  topic_id: string;
  questions_attempted: number;
  questions_correct: number;
  skill_level: 'not_started' | 'learning' | 'practicing' | 'mastered';
  confidence_score: number;
  strengths?: string[];
  weaknesses?: string[];
  notes?: string;
}

// =============================================================================
// SESSION TYPES
// =============================================================================

/**
 * Learning session state
 */
export interface SessionState {
  session_id: string;
  student_id: string;
  topic_id: string;
  status: 'in_progress' | 'completed' | 'abandoned';
  started_at: string;
  current_question_index: number;
  questions: GeneratedQuestion[];
  answers: AnswerSubmission[];
  conversation_history: ConversationMessage[];
}

/**
 * Session performance summary
 */
export interface SessionSummary {
  total_questions: number;
  questions_correct: number;
  accuracy: number;
  time_spent_seconds: number;
  topics_mastered: string[];
  areas_to_improve: string[];
  encouragement: string;
}

// =============================================================================
// CONVERSATION TYPES
// =============================================================================

/**
 * Conversation message
 */
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: string;
}

/**
 * Chat request
 */
export interface ChatRequest {
  session_id: string;
  message: string;
  current_question: string;
  context: TutoringContext;
}

/**
 * Chat response
 */
export interface ChatResponse {
  message: string;
  role: 'assistant';
}

// =============================================================================
// API TYPES
// =============================================================================

/**
 * API request for generating questions
 */
export interface GenerateQuestionsRequest {
  student_id: string;
  topic_id: string;
  num_questions?: number;
}

/**
 * API response for generating questions
 */
export interface GenerateQuestionsResponse {
  success: boolean;
  questions?: GeneratedQuestion[];
  error?: string;
}

/**
 * API request for evaluating an answer
 */
export interface EvaluateAnswerRequest {
  session_id: string;
  question_id: string;
  question_text: string;
  correct_answer: string;
  student_answer: string;
  student_id: string;
  topic_id: string;
  time_spent_seconds: number;
  hints_used: number;
}

/**
 * API response for evaluating an answer
 */
export interface EvaluateAnswerResponse {
  success: boolean;
  evaluation?: AnswerEvaluation;
  progress_update?: ProgressUpdate;
  error?: string;
}

/**
 * API request for starting a session
 */
export interface StartSessionRequest {
  student_id: string;
  topic_id: string;
  session_type?: 'guided_practice' | 'assessment' | 'review';
}

/**
 * API response for starting a session
 */
export interface StartSessionResponse {
  success: boolean;
  session?: {
    session_id: string;
    questions: GeneratedQuestion[];
  };
  error?: string;
}

/**
 * API request for completing a session
 */
export interface CompleteSessionRequest {
  session_id: string;
}

/**
 * API response for completing a session
 */
export interface CompleteSessionResponse {
  success: boolean;
  summary?: SessionSummary;
  error?: string;
}

// =============================================================================
// UI STATE TYPES
// =============================================================================

/**
 * Loading states for UI
 */
export type LoadingState = 'idle' | 'loading' | 'success' | 'error';

/**
 * Question display state
 */
export interface QuestionState {
  question: GeneratedQuestion;
  questionIndex: number;
  totalQuestions: number;
  studentAnswer: string;
  hintsRevealed: number;
  timeStarted: number;
  isSubmitting: boolean;
  evaluation: AnswerEvaluation | null;
  showFeedback: boolean;
}

/**
 * Dashboard data
 */
export interface DashboardData {
  student: Student;
  topics: Array<{
    topic: CurriculumTopic;
    progress: {
      skill_level: string;
      confidence_score: number;
      questions_attempted: number;
      questions_correct: number;
    } | null;
  }>;
  current_session: {
    session_id: string;
    topic: CurriculumTopic;
    questions_completed: number;
  } | null;
  stats: {
    total_questions: number;
    correct_questions: number;
    accuracy: number;
    topics_mastered: number;
    total_sessions: number;
  };
}

// =============================================================================
// UTILITY TYPES
// =============================================================================

/**
 * Skill level progression
 */
export const SKILL_LEVELS = [
  'not_started',
  'learning',
  'practicing',
  'mastered',
] as const;

/**
 * Difficulty levels
 */
export const DIFFICULTY_LEVELS = ['easy', 'medium', 'hard'] as const;

/**
 * Question types
 */
export const QUESTION_TYPES = [
  'multiple_choice',
  'short_answer',
  'problem_solving',
] as const;

/**
 * Grade levels (Victorian Curriculum)
 */
export const GRADE_LEVELS = [
  'Year_4',
  'Year_5',
  'Year_6',
  'Year_7',
  'Year_8',
  'Year_9',
  'Year_10',
] as const;

/**
 * Curriculum strands
 */
export const CURRICULUM_STRANDS = [
  'Number',
  'Algebra',
  'Measurement',
  'Space',
  'Statistics',
  'Probability',
] as const;
